// Pokemon pixel art sprites (16x16 front and back views)
// Each character maps to a color in the palette
const PokemonSprites = {
    // Bulbasaur front
    bulbasaur_front: [
        '................',
        '......gggg......',
        '.....gGGGGg.....',
        '....gGGGGGGg....',
        '...gGGGGGGGGg...',
        '..ggGGGGGGGggg..',
        '.gGgggGGGggGGGg.',
        '.gGG0ggggg0GGGg.',
        '.gGG00gggg00GGg.',
        '..gGGGgFFgGGGg..',
        '..gGGGgFFgGGGg..',
        '...gGGGggGGGg...',
        '....gGGGGGGg....',
        '.....gggggg.....',
        '................',
        '................'
    ],
    bulbasaur_back: [
        '................',
        '.....gggggg.....',
        '....gGGGGGGg....',
        '...gGGGGGGGGg...',
        '..gGGGGGGGGGGg..',
        '..gGGGGGGGGGGg..',
        '..ggGGGGGGGGgg..',
        '...gggGGGGggg...',
        '....gGGGGGGg....',
        '....gGGGGGGg....',
        '.....gGGGGg.....',
        '.....gggggg.....',
        '................',
        '................',
        '................',
        '................'
    ],

    charmander_front: [
        '................',
        '......OOOO......',
        '.....OOoOOO.....',
        '....OOOOOOOo....',
        '....OO0OO0OO....',
        '....OO00OO00....',
        '....OOOOFFOo....',
        '.....OOFFFFo....',
        '.....OOOOOO.....',
        '....OOOOOOOo....',
        '....OOOOOOOo....',
        '.....OOOOOO.....',
        '......OOOO.rR...',
        '......OO.O.Rr...',
        '.......OO..R....',
        '................'
    ],
    charmander_back: [
        '................',
        '.....OOOOO......',
        '....OOOOOOo.....',
        '...OOOOOOOOo....',
        '...OOOOOOOOo....',
        '....OOOOOOOo....',
        '....OOOOOOo.....',
        '.....OOOOOo.....',
        '.....OOOOOo.....',
        '......OOOOo.....',
        '......OOOO.rR...',
        '.......OOO.Rr...',
        '.......OO..R....',
        '................',
        '................',
        '................'
    ],

    squirtle_front: [
        '................',
        '......BBBB......',
        '.....BBbBBB.....',
        '....BBBBBBBb....',
        '....BB0BB0BB....',
        '....BB00BB00....',
        '....BBBBFFBb....',
        '.....BBFFFFb....',
        '..YYyBBBBBB.....',
        '.YYYyBBBBBBb....',
        '.YYYyBBBBBBb....',
        '..YYyBBBBBBb....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......BB.B......',
        '................'
    ],
    squirtle_back: [
        '................',
        '.....BBBBB......',
        '....BBBBBBb.....',
        '...BBBBBBBBb....',
        '...BBBBBBBBb....',
        '..YYyBBBBBBb....',
        '.YYYyBBBBBb.....',
        '.YYYyBBBBBb.....',
        '..YYyBBBBBb.....',
        '.....BBBBBb.....',
        '......BBBBb.....',
        '.......BBBb.....',
        '................',
        '................',
        '................',
        '................'
    ],

    ivysaur_front: [
        '......RRRR......',
        '.....RRrrRR.....',
        '....gGRRRRGg....',
        '...gGGGGGGGGg...',
        '..gGGGGGGGGGGg..',
        '..gGgGGGGGGgGg..',
        '.gGG0gggggg0GGg.',
        '.gGG00gggg00GGg.',
        '..gGGGgFFgGGGg..',
        '..gGGGgFFgGGGg..',
        '...gGGGggGGGg...',
        '....gGGGGGGg....',
        '.....gggggg.....',
        '................',
        '................',
        '................'
    ],
    ivysaur_back: [
        '.....RRRRRR.....',
        '....RRRrrRRR....',
        '...gGGRRRRGGg...',
        '..gGGGGGGGGGGg..',
        '..gGGGGGGGGGGg..',
        '...ggGGGGGGgg...',
        '....gGGGGGGg....',
        '....gGGGGGGg....',
        '.....gGGGGg.....',
        '.....gggggg.....',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    venusaur_front: [
        '....RRRRRRRR....',
        '...RRRRrrRRRR...',
        '..RRRRRRRRRRRg..',
        '.gGGGRRRRGGGGg..',
        '.gGGGGGGGGGGGGg.',
        'gGGGgGGGGGGgGGg.',
        'gGG0ggggggg0GGGg',
        'gGG00ggggg00GGGg',
        '.gGGGggFFgGGGGg.',
        '.gGGGGFFGGGGGg..',
        '..gGGGGGGGGGg...',
        '...gGGGGGGGg....',
        '....gggggggg....',
        '................',
        '................',
        '................'
    ],
    venusaur_back: [
        '...RRRRRRRRRR...',
        '..RRRRRrrRRRRR..',
        '.gGGRRRRRRRGGGg.',
        '.gGGGGGGGGGGGGg.',
        'gGGGGGGGGGGGGGg.',
        'gGGGGGGGGGGGGg..',
        '.ggGGGGGGGGgg...',
        '..gGGGGGGGGg....',
        '..gGGGGGGGGg....',
        '...gGGGGGGg.....',
        '...gggggggg.....',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    charmeleon_front: [
        '................',
        '.....OOOOOo.....',
        '....OOOoOOOo....',
        '...OOOOOOOOOo...',
        '...OO0OOO0OOo...',
        '...OO00OOO00o...',
        '...OOOOOFFOOo...',
        '....OOOFFFFo....',
        '....OOOOOOOo....',
        '...OOOOOOOOOo...',
        '...OOOOOOOOOo...',
        '....OOOOOOO.....',
        '.....OOOOO.rRR..',
        '.....OO..O.RRr..',
        '......OO...RR...',
        '................'
    ],
    charmeleon_back: [
        '....OOOOO.......',
        '...OOOOOOo......',
        '..OOOOOOOOo.....',
        '..OOOOOOOOo.....',
        '...OOOOOOOo.....',
        '...OOOOOOo......',
        '....OOOOOo......',
        '....OOOOOo......',
        '.....OOOOo......',
        '.....OOOO.rRR...',
        '......OOO.RRr...',
        '......OO..RR....',
        '................',
        '................',
        '................',
        '................'
    ],

    charizard_front: [
        '..PP.......PP...',
        '..PPP.....PPP...',
        '...OOOOOOOOo....',
        '..OOOOoOOOOOo...',
        '..OO0OOOO0OOo...',
        '..OO00OOO00Oo...',
        '..OOOOOFFOOo....',
        '...OOOFFFFo.....',
        '...OOOOOOOo.....',
        '..OOOOOOOOOo....',
        '.OOOOOOOOOOOo...',
        '..OOOOOOOOOo.rR.',
        '...OOOOOOO..Rr..',
        '....OO..OO..R...',
        '.....OO..O......',
        '................'
    ],
    charizard_back: [
        '..PP......PP....',
        '..PPP....PPP....',
        '...OOOOOOOO.....',
        '..OOOOOOOOOo....',
        '..OOOOOOOOOo....',
        '...OOOOOOOOo....',
        '...OOOOOOOo.....',
        '....OOOOOOo.....',
        '....OOOOOOo.....',
        '.....OOOOOo.....',
        '.....OOOOO.rRR..',
        '......OOOO.RRr..',
        '......OOO..RR...',
        '................',
        '................',
        '................'
    ],

    wartortle_front: [
        '.......PPPP.....',
        '......PPpPP.....',
        '.....BBBBBBb....',
        '....BBBbBBBBb...',
        '....BB0BBB0Bb...',
        '....BB00BB00b...',
        '....BBBBBFFb....',
        '.YYyBBFFFFBb....',
        'YYYYyBBBBBBb....',
        'YYYYyBBBBBBBb...',
        '.YYYyBBBBBBBb...',
        '..YYyBBBBBBb....',
        '.....BBBBBBb....',
        '......BBBB......',
        '......BB.BB.....',
        '................'
    ],
    wartortle_back: [
        '......PPPP......',
        '.....PPpPPP.....',
        '....BBBBBBBb....',
        '...BBBBBBBBBb...',
        '...BBBBBBBBBb...',
        '..YYyBBBBBBBb...',
        '.YYYyBBBBBBb....',
        '.YYYyBBBBBBb....',
        '..YYyBBBBBBb....',
        '......BBBBBb....',
        '.......BBBBb....',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    blastoise_front: [
        '...cc.....cc....',
        '..ccc.....ccc...',
        '..ccBBBBBBBcc...',
        '...BBBbBBBBBb...',
        '...BB0BBB0BBb...',
        '...BB00BB00Bb...',
        '...BBBBBFFBb....',
        'YYYyBBFFFFBb....',
        'YYYYyBBBBBBb....',
        'YYYYyBBBBBBBb...',
        '.YYYyBBBBBBBb...',
        '..YYyBBBBBBb....',
        '.....BBBBBBb....',
        '......BBBB......',
        '......BB.BB.....',
        '................'
    ],
    blastoise_back: [
        '..ccc....ccc....',
        '..ccc....ccc....',
        '...BBBBBBBBb....',
        '..BBBBBBBBBBb...',
        '..BBBBBBBBBBb...',
        '.YYyBBBBBBBBb...',
        'YYYyBBBBBBBb....',
        'YYYyBBBBBBBb....',
        '.YYyBBBBBBBb....',
        '......BBBBBb....',
        '.......BBBBb....',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    pidgey_front: [
        '................',
        '.......11.......',
        '......1ss1......',
        '.....1ssss1.....',
        '....1s0ss0s1....',
        '....1s00s00s....',
        '....1ssssFss....',
        '..111ssFFss1....',
        '.1sss1ssss1.....',
        '..1ss1ssss1.....',
        '...11sssss1.....',
        '.....1sss1......',
        '......111.......',
        '......1.1.......',
        '................',
        '................'
    ],
    pidgey_back: [
        '................',
        '......1111......',
        '.....1ssss1.....',
        '....1ssssss1....',
        '..1s1ssssss1....',
        '.1ss1ssssss1....',
        '..11ssssssss1...',
        '.....1sssss1....',
        '......1sss1.....',
        '......11111.....',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    pidgeotto_front: [
        '......RR........',
        '.....RRR1.......',
        '....1ssss1......',
        '...1ssssss1.....',
        '...1s0ss0ss1....',
        '...1s00ss00s....',
        '...1sssssFs1....',
        '.1111ssFFs1.....',
        '1ssss1ssss1.....',
        '.1sss1ssss1.....',
        '..111sssss1.....',
        '.....1ssss1.....',
        '......111.......',
        '......1..1......',
        '................',
        '................'
    ],
    pidgeotto_back: [
        '.....RRR........',
        '....RRR11.......',
        '...1ssssss1.....',
        '..1ssssssss1....',
        '.1ss1ssssss1....',
        '1sss1sssssss1...',
        '.111sssssssss1..',
        '......1ssssss1..',
        '.......1ssss1...',
        '........1111....',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    pidgeot_front: [
        '.....RRR........',
        '....RRRR1.......',
        '...1Yssss1......',
        '..1Ysssss s1....',
        '..1Ys0ss0ss1....',
        '..1Ys00ss00s....',
        '..11sssssFs1....',
        '.11111sFFs1.....',
        '1sssss1sss1.....',
        '.1ssss1sss1.....',
        '..1111ssss1.....',
        '......1sss1.....',
        '.......111......',
        '.......1..1.....',
        '................',
        '................'
    ],
    pidgeot_back: [
        '....RRRR........',
        '...RRRRR1.......',
        '..1Yssssss1.....',
        '.1Ysssssss s1...',
        '1Yss1ssssssss1..',
        '1sss1sssssssss1.',
        '.111ssssssssss1.',
        '.......1ssssss1.',
        '........1ssss1..',
        '.........1111...',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    rattata_front: [
        '................',
        '................',
        '...PP.....PP....',
        '...PP.....PP....',
        '....PPPPPP P....',
        '....P0PPP0P.....',
        '....P00PP00.....',
        '....PPPPFFp.....',
        '....PPFFFFp.....',
        '.....PPPPPPp....',
        '.....PPPPPPp....',
        '......PPPP......',
        '.......PP.......',
        '................',
        '................',
        '................'
    ],
    rattata_back: [
        '................',
        '....PPP.PPP.....',
        '...PP.....PP....',
        '....PPPPPPP.....',
        '....PPPPPPPp....',
        '....PPPPPPPp....',
        '.....PPPPPp.....',
        '.....PPPPPp.....',
        '......PPPPp.....',
        '.......PPP......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    raticate_front: [
        '..PP.......PP...',
        '..PP.......PP...',
        '...PPPPPPPPP....',
        '...P0PPPP0PPp...',
        '...P00PPP00Pp...',
        '...PPPPPFFPPp...',
        '...PPP3FF3PPp...',
        '....PPPPPPPPp...',
        '....PPPPPPPPp...',
        '.....PPPPPPp....',
        '......PPPPP.....',
        '.......PPP......',
        '................',
        '................',
        '................',
        '................'
    ],
    raticate_back: [
        '..PP.......PP...',
        '..PPP.....PPP...',
        '...PPPPPPPPP....',
        '...PPPPPPPPPp...',
        '....PPPPPPPPp...',
        '....PPPPPPPp....',
        '.....PPPPPPp....',
        '.....PPPPPp.....',
        '......PPPP......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    pikachu_front: [
        '..Y..........Y..',
        '..YY........YY..',
        '...YY......YY...',
        '...YYYYYYYY.....',
        '..YYYYyYYYYY....',
        '..YY0YYYY0YY....',
        '..YY00YYY00Y....',
        '..RYYYYFFYYy....',
        '..YYYYFFFYYY....',
        '...YYYYYYYYYY...',
        '...YYYYYYYYYy...',
        '....YYYYYYYy....',
        '.....YYYYYy.....',
        '......YYYY......',
        '......YY.Y......',
        '................'
    ],
    pikachu_back: [
        '..0Y.........Y0.',
        '...YY.......YY..',
        '....YY.....YY...',
        '....YYYYYYYYY...',
        '...YYYYYyYYYYY..',
        '...YYYYYYYYYYy..',
        '...YYYYYYYYY0Y..',
        '...YYYYYYYYy0Y..',
        '....YYYYYYYy....',
        '.....YYYYYYY....',
        '......YYYYYy....',
        '.......YYYY.....',
        '................',
        '................',
        '................',
        '................'
    ],

    caterpie_front: [
        '................',
        '.......GG.......',
        '......GGGg......',
        '.....GG0GGg.....',
        '.....G00G0g.....',
        '.....GGGGGg.....',
        '......GGGg......',
        '.....GGGGGg.....',
        '....GGGGGGGg....',
        '.....GGGGGg.....',
        '......GGGg......',
        '.......GGg......',
        '................',
        '................',
        '................',
        '................'
    ],
    caterpie_back: [
        '................',
        '.......GG.......',
        '......GGGg......',
        '.....GGGGGg.....',
        '......GGGg......',
        '.....GGGGGg.....',
        '....GGGGGGGg....',
        '.....GGGGGg.....',
        '......GGGg......',
        '.......GGg......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    metapod_front: [
        '................',
        '......GGGg......',
        '.....GGGGGg.....',
        '....GGGGGGGg....',
        '...GGGGG0GGGg...',
        '..GGGGGGGGGGGg..',
        '..GGGGGGGGGGGg..',
        '...GGGGGGGGGg...',
        '....GGGGGGGg....',
        '.....GGGGGg.....',
        '......GGGg......',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],
    metapod_back: [
        '................',
        '......GGGg......',
        '.....GGGGGg.....',
        '....GGGGGGGg....',
        '...GGGGGGGGGg...',
        '..GGGGGGGGGGGg..',
        '..GGGGGGGGGGGg..',
        '...GGGGGGGGGg...',
        '....GGGGGGGg....',
        '.....GGGGGg.....',
        '......GGGg......',
        '................',
        '................',
        '................',
        '................',
        '................'
    ],

    butterfree_front: [
        '..33.......33...',
        '.3333.....3333..',
        '33B3333.3333B33.',
        '3BBB3333333BBB3.',
        '.3BB333R333BB3..',
        '..333333333333..',
        '...33B3B3B33....',
        '....333B333.....',
        '.....33333......',
        '..33..BBB..33...',
        '.33B33BBB3B33...',
        '33BB333B333BB3..',
        '.3B33.BBB.33B3..',
        '..33...B...33...',
        '................',
        '................'
    ],
    butterfree_back: [
        '..33.......33...',
        '.3333.....3333..',
        '33B333.333B333..',
        '3BBB33.33BBB33..',
        '.3BB3333BB333...',
        '..3333333333....',
        '...33BBB33......',
        '....3BBB3.......',
        '..33.BBB.33.....',
        '.33B3BBB3B33....',
        '33BB33B33BB33...',
        '.3B33.B.33B3....',
        '..33.....33.....',
        '................',
        '................',
        '................'
    ],

    // Generic sprites for Pokemon without specific art
    _generateGeneric(type1, size = 'medium') {
        const tc = TYPE_COLORS[type1] || '#a8a878';
        const r = parseInt(tc.slice(1, 3), 16);
        const g = parseInt(tc.slice(3, 5), 16);
        const b = parseInt(tc.slice(5, 7), 16);

        // Create a simple blob sprite colored by type
        const palette = {
            '.': null,
            'M': [r, g, b],
            'm': [Math.floor(r * 0.7), Math.floor(g * 0.7), Math.floor(b * 0.7)],
            'L': [Math.min(255, Math.floor(r * 1.3)), Math.min(255, Math.floor(g * 1.3)), Math.min(255, Math.floor(b * 1.3))],
            '0': [24, 24, 24],
            '3': [248, 248, 248]
        };

        const sprite = [
            '................',
            '......MMMM......',
            '.....MMmMMM.....',
            '....MMMmMMMM....',
            '...MMMMMMMMMm...',
            '...MM0MMM0MMm...',
            '...MM00MM00Mm...',
            '...MMMMMFFMMm...',
            '....MMMFFMMMm...',
            '....MMMMMMMm....',
            '...MMMMMMMMm....',
            '...MMMMMMMm.....',
            '....MMMMMMm.....',
            '.....mmmm.......',
            '................',
            '................'
        ];
        return { sprite, palette };
    },

    getSprite(pokemonId, facing = 'front') {
        const key = pokemonId + '_' + facing;
        if (this[key]) {
            return { sprite: this[key], palette: null };
        }

        // Generate generic sprite based on type
        const pokemon = PokemonDB[pokemonId];
        if (pokemon) {
            return this._generateGeneric(pokemon.types[0]);
        }

        return this._generateGeneric('Normal');
    }
};

// Add missing sprites using generic generation
const pokemonWithoutSprites = ['weedle', 'kakuna', 'beedrill', 'nidoran_m', 'nidorino',
    'zubat', 'golbat', 'oddish', 'gloom', 'poliwag', 'poliwhirl', 'machop', 'machoke',
    'geodude', 'graveler', 'gastly', 'haunter', 'abra', 'kadabra', 'growlithe',
    'magikarp', 'gyarados', 'eevee', 'snorlax', 'dratini', 'dragonair'];

pokemonWithoutSprites.forEach(id => {
    if (PokemonDB[id]) {
        const gen = PokemonSprites._generateGeneric(PokemonDB[id].types[0]);
        PokemonSprites[id + '_front'] = gen.sprite;
        PokemonSprites[id + '_back'] = gen.sprite;
    }
});
